// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnMlPGtNLcWon7QOBHRLAGHew0JGQekwc',
    appId: '1:686752998334:web:97bd1a1502a1b6e3c90fef',
    messagingSenderId: '686752998334',
    projectId: 'blogspoter',
    authDomain: 'blogspoter.firebaseapp.com',
    storageBucket: 'blogspoter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4rcKWKxGEg3HiNT4UFGyzRAaY3n24yg',
    appId: '1:686752998334:android:2e9ac66fda36b0c2c90fef',
    messagingSenderId: '686752998334',
    projectId: 'blogspoter',
    storageBucket: 'blogspoter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHsvhk7uAD4XOdNvheZojgMnKeDlIAXEo',
    appId: '1:686752998334:ios:3691773aad026c09c90fef',
    messagingSenderId: '686752998334',
    projectId: 'blogspoter',
    storageBucket: 'blogspoter.appspot.com',
    iosBundleId: 'com.example.blogspoter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHsvhk7uAD4XOdNvheZojgMnKeDlIAXEo',
    appId: '1:686752998334:ios:dfd821ba3c86265fc90fef',
    messagingSenderId: '686752998334',
    projectId: 'blogspoter',
    storageBucket: 'blogspoter.appspot.com',
    iosBundleId: 'com.example.blogspoter.RunnerTests',
  );
}
